version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-management-api
    volumes:
      - ./log-data:/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpass
      TZ: Asia/Bangkok
    ports:
      - "8080:8080"
    networks:
      - book-network

networks:
  book-network:
    external: true
